/* Copyright 2020 Natan Junges

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

#ifndef MULTIBOOT2_H
#define MULTIBOOT2_H

#define MULTIBOOT2_HEADER_MAGIC 0xE85250D6

#define MULTIBOOT2_HEADER_ARCHITECTURE 0

#define MULTIBOOT2_HEADER_TAG_TYPE_END 0
#define MULTIBOOT2_HEADER_TAG_TYPE_INFORMATION_REQUEST 1
#define MULTIBOOT2_HEADER_TAG_TYPE_FRAMEBUFFER 5
#define MULTIBOOT2_HEADER_TAG_TYPE_MODULE_ALIGNMENT 6
#define MULTIBOOT2_HEADER_TAG_TYPE_EFI_BOOT_SERVICES 7
#define MULTIBOOT2_HEADER_TAG_TYPE_EFI_I386_ENTRY_ADDRESS 8
#define MULTIBOOT2_HEADER_TAG_TYPE_EFI_AMD64_ENTRY_ADDRESS 9
#define MULTIBOOT2_HEADER_TAG_TYPE_RELOCATABLE_HEADER 10

#define MULTIBOOT2_HEADER_TAG_FLAGS_OPTIONAL (1 << 0)

#define MULTIBOOT2_HEADER_TAG_RELOCATABLE_HEADER_PREFERENCE_NONE 0
#define MULTIBOOT2_HEADER_TAG_RELOCATABLE_HEADER_PREFERENCE_LOWEST 1
#define MULTIBOOT2_HEADER_TAG_RELOCATABLE_HEADER_PREFERENCE_HIGHEST 2

#define MULTIBOOT2_MAGIC 0x36D76289

#define MBI_TAG_TYPE_END 0
#define MBI_TAG_TYPE_BOOT_COMMAND_LINE 1
#define MBI_TAG_TYPE_BOOT_LOADER_NAME 2
#define MBI_TAG_TYPE_MODULES 3
#define MBI_TAG_TYPE_BASIC_MEMORY_INFORMATION 4
#define MBI_TAG_TYPE_MEMORY_MAP 6
#define MBI_TAG_TYPE_FRAMEBUFFER_INFO 8
#define MBI_TAG_TYPE_ELF_SYMBOLS 9
#define MBI_TAG_TYPE_EFI_32_BIT_SYSTEM_TABLE_POINTER 11
#define MBI_TAG_TYPE_EFI_64_BIT_SYSTEM_TABLE_POINTER 12
#define MBI_TAG_TYPE_SMBIOS_TABLES 13
#define MBI_TAG_TYPE_ACPI_OLD_RSDP 14
#define MBI_TAG_TYPE_ACPI_NEW_RSDP 15
#define MBI_TAG_TYPE_NETWORKING_INFORMATION 16
#define MBI_TAG_TYPE_EFI_MEMORY_MAP 17
#define MBI_TAG_TYPE_EFI_BOOT_SERVICES_NOT_TERMINATED 18
#define MBI_TAG_TYPE_EFI_32_BIT_IMAGE_HANDLE_POINTER 19
#define MBI_TAG_TYPE_EFI_64_BIT_IMAGE_HANDLE_POINTER 20
#define MBI_TAG_TYPE_IMAGE_LOAD_BASE_PHYSICAL_ADDRESS 21

#endif/* !MULTIBOOT2_H*/
